# Generated by Django 5.2.7 on 2026-03-25 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_customuser_minutos_conectado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiapositivaTeoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloque_id', models.IntegerField()),
                ('orden', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='teoria/')),
            ],
            options={
                'ordering': ['bloque_id', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='IntentoEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloque_id', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('aciertos', models.IntegerField()),
                ('fallos', models.IntegerField()),
                ('detalle_ejercicio', models.JSONField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
