# Generated by Django 5.2.7 on 2026-03-27 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_diapositivateoria_intentoejercicio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiapositivaTeoria',
        ),
    ]
