# Generated by Django 5.2.7 on 2026-04-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_delete_diapositivateoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intentoejercicio',
            name='aciertos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='intentoejercicio',
            name='detalle_ejercicio',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intentoejercicio',
            name='fallos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='intentoejercicio',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='intentoejercicio',
            unique_together={('usuario', 'bloque_id')},
        ),
    ]
