# Generated by Django 5.2.7 on 2026-04-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_intentoejercicio_aciertos_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='intentoejercicio',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='intentoejercicio',
            name='aciertos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='intentoejercicio',
            name='detalle_ejercicio',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='intentoejercicio',
            name='fallos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='intentoejercicio',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
